-- Insert demo braid entries for testing
INSERT INTO braids (
  braid_name, 
  alt_names, 
  region, 
  image_url, 
  contributor_name, 
  submission_type,
  public_url,
  link_title,
  link_description,
  memory_title,
  memory_description,
  created_at
) VALUES 
(
  'Box Braids',
  'Poetic Justice Braids, Square Braids',
  'West Africa',
  '/placeholder.svg?height=400&width=300&text=Box+Braids',
  'Maya Johnson',
  'photo',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '2 days'
),
(
  'Goddess Braids Tutorial',
  'Crown Braids, Halo Braids',
  'Ancient Egypt',
  '/placeholder.svg?height=400&width=300&text=Goddess+Braids',
  'Aisha Williams',
  'link',
  'https://www.youtube.com/watch?v=example',
  'Complete Goddess Braids Tutorial',
  'Step-by-step guide to creating beautiful goddess braids with cornrow base and loose braided extensions.',
  NULL,
  NULL,
  NOW() - INTERVAL '1 day'
),
(
  'Grandmother''s Braiding Wisdom',
  NULL,
  'Southern United States',
  NULL,
  'Keisha Brown',
  'memory',
  NULL,
  NULL,
  NULL,
  'Sunday Braiding Sessions',
  'Every Sunday after church, my grandmother would sit me between her knees on the living room floor. She would part my hair with the precision of an artist, her fingers moving through each section like she was weaving stories into my scalp. She taught me that braiding wasn''t just about hair - it was about connection, tradition, and the sacred time we spent together. Those moments shaped who I am today.',
  NOW() - INTERVAL '3 hours'
),
(
  'Fulani Braids',
  'Tribal Braids, Fulani Cornrows',
  'West Africa - Fulani People',
  '/placeholder.svg?height=400&width=300&text=Fulani+Braids',
  'Fatima Diallo',
  'photo',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NOW() - INTERVAL '5 hours'
),
(
  'Learning to Braid',
  NULL,
  'Caribbean',
  NULL,
  'Marley Thompson',
  'memory',
  NULL,
  NULL,
  NULL,
  'First Time Braiding My Sister',
  'I was twelve when my mother finally trusted me to braid my little sister''s hair for school. My hands shook as I tried to recreate the neat cornrows I had watched her do a thousand times. It took me three hours and looked nothing like mama''s work, but my sister wore those crooked braids with pride. That day, I understood that braiding was about more than technique - it was about love, patience, and the trust someone places in your hands.',
  NOW() - INTERVAL '6 hours'
);
